# Generated by Django 2.0.3 on 2018-05-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_auto_20180507_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='tin_number',
            field=models.IntegerField(),
        ),
    ]
