# Generated by Django 2.0.3 on 2018-05-07 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_auto_20180507_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='tin_number',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
