# Generated by Django 2.0.3 on 2018-05-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0005_auto_20180507_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='tin_number',
            field=models.IntegerField(),
        ),
    ]
