# Generated by Django 2.0.3 on 2018-05-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0006_auto_20180507_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
