# Generated by Django 2.0.3 on 2018-05-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_branch', '0005_auto_20180509_1743'),
        ('material_master', '0002_material_is_sales'),
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('material_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('company_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_branch.CompanyBranch')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_master.Material')),
                ('po_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_detail', to='purchase_order.PurchaseOrder')),
                ('storage_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_branch.StorageBin')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_branch.StorageLocation')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_branch.UOM')),
            ],
        ),
    ]
