# Generated by Django 2.0.3 on 2018-05-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20180514_1542'),
        ('vendor', '0003_auto_20180515_1409'),
        ('gstrates', '0001_initial'),
        ('purchase_order', '0002_purchaseorderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderFreight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight_option', models.CharField(blank=True, choices=[('1', 'Vendor'), ('2', 'Own')], default=None, max_length=1, null=True)),
                ('freight_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freight_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('freight_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('freight_gst_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gstrates.GSTrates')),
                ('po_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_freight', to='purchase_order.PurchaseOrder')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(max_length=255)),
                ('po_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_map', to='purchase_order.PurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_terms', to='purchase_order.PurchaseOrder')),
                ('po_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.TermsandConditon')),
            ],
        ),
    ]
