# Generated by Django 2.0.3 on 2018-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_purchaseorderfreight_purchaseordermap_purchaseorderterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
    ]
