# Generated by Django 2.0.3 on 2018-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_auto_20180515_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation_date',
            field=models.DateTimeField(),
        ),
    ]
