# Generated by Django 2.0.3 on 2018-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_auto_20180515_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation_no',
            field=models.CharField(max_length=200),
        ),
    ]
