# Generated by Django 2.0.3 on 2018-06-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
