# Generated by Django 2.0.3 on 2018-05-19 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0007_auto_20180515_1906'),
        ('payment', '0002_payment_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='po_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_order.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='po_order_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_order.PurchaseOrderMap'),
        ),
    ]
