# Generated by Django 2.0.3 on 2018-05-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20180519_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='po_order_no',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
