# Generated by Django 2.0.3 on 2018-05-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_refrence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='po_order_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purchase_inv_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
