# Generated by Django 2.0.3 on 2018-05-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20180531_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='special_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
