# Generated by Django 2.0.3 on 2018-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20180531_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmap',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
