# Generated by Django 2.0.3 on 2018-05-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='contact_person',
        ),
    ]
