# Generated by Django 2.0.3 on 2018-05-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_auto_20180531_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='pan_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
