# Generated by Django 2.0.3 on 2018-05-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0004_auto_20180531_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
