# Generated by Django 2.0.3 on 2018-05-28 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designation', '0001_initial'),
        ('states', '0006_auto_20180507_1514'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
        ('company', '0008_auto_20180514_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('dob', models.DateTimeField()),
                ('alt_contact', models.BigIntegerField()),
                ('pan', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('epf_status', models.BooleanField(default=False)),
                ('epf_no', models.CharField(max_length=100)),
                ('emp_present_address', models.CharField(max_length=255)),
                ('emp_present_city', models.CharField(max_length=100)),
                ('emp_present_pin', models.CharField(max_length=100)),
                ('emp_permanent_address', models.CharField(max_length=255)),
                ('emp_permanent_city', models.CharField(max_length=100)),
                ('emp_permanent_pin', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('departments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.Departments')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designation.Designation')),
                ('emp_permanent_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_state', to='states.State')),
                ('emp_present_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='present_state', to='states.State')),
            ],
        ),
    ]
