# Generated by Django 2.0.3 on 2018-05-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adhaar_no',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
    ]
