# Generated by Django 2.0.3 on 2018-06-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20180604_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='alt_contact',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(default=8013134344, max_length=255),
            preserve_default=False,
        ),
    ]
