# Generated by Django 2.0.3 on 2018-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
