# Generated by Django 2.0.3 on 2018-05-09 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_branch', '0004_auto_20180508_1448'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchaseorggroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrgMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_branch.CompanyBranch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pur_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseorggroup.PurchaseOrg')),
            ],
        ),
    ]
