# Generated by Django 2.0.3 on 2018-05-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
