# Generated by Django 2.0.3 on 2018-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_sales',
            field=models.BooleanField(default=False),
        ),
    ]
