# Generated by Django 2.0.3 on 2018-06-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_master', '0002_material_is_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material_tax',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material_uom',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialpurchasegroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialpurchaseorg',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
