# Generated by Django 2.0.3 on 2018-06-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_master', '0004_materialtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
