# Generated by Django 2.0.3 on 2018-05-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requisition', '0002_auto_20180514_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='requisition_no',
            field=models.CharField(default='2018-05-15/I-001', max_length=255),
            preserve_default=False,
        ),
    ]
