# Generated by Django 2.0.3 on 2018-05-15 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requisition', '0003_requisition_requisition_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='requisition_no',
        ),
        migrations.AddField(
            model_name='requisitionmap',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_map', to='purchase_requisition.Requisition'),
        ),
    ]
