# Generated by Django 2.0.3 on 2018-05-15 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requisition', '0004_auto_20180515_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_company', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='purchase_grp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_pur_grp', to='purchaseorggroup.PurchaseGroup'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='purchase_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_pur_org', to='purchaseorggroup.PurchaseOrg'),
        ),
    ]
