# Generated by Django 2.0.3 on 2018-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requisition', '0005_auto_20180515_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='is_approve',
            field=models.CharField(choices=[('1', 'Finalised'), ('2', 'Approved'), ('3', 'None')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='is_finalised',
            field=models.CharField(choices=[('1', 'Finalised'), ('2', 'Approved'), ('3', 'None')], default='3', max_length=1),
        ),
    ]
