# Generated by Django 2.0.3 on 2018-05-07 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('states', '0003_auto_20180507_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_url', models.URLField()),
                ('company_gst', models.CharField(max_length=50)),
                ('company_pan', models.CharField(max_length=50)),
                ('company_cin', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=50)),
                ('company_address', models.CharField(max_length=100)),
                ('company_contact', models.BigIntegerField()),
                ('company_city', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='states.State')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
