# Generated by Django 2.0.3 on 2018-05-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180507_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
