# Generated by Django 2.0.3 on 2018-05-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20180507_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
