# Generated by Django 2.0.3 on 2018-05-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_company_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_pin',
            field=models.CharField(max_length=50),
        ),
    ]
