# Generated by Django 2.0.3 on 2018-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_termsandconditon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditon',
            name='term_type',
            field=models.CharField(blank=True, choices=[('1', 'Payment'), ('2', 'Delivery'), ('3', 'Others')], default=None, max_length=1, null=True),
        ),
    ]
