# Generated by Django 2.0.3 on 2018-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20180514_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_url',
            field=models.CharField(max_length=255),
        ),
    ]
