# Generated by Django 2.0.3 on 2018-05-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20180529_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='termsandconditon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
