# Generated by Django 2.0.3 on 2018-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstrates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstrates',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
